const { MongoClient, ObjectId } = require("mongodb");
require("dotenv").config({ path: ".env.local" });

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://127.0.0.1:27017";
const DB_NAME = process.env.MONGODB_DB || "worldforge";

// System user for seeding
const SYSTEM_USER_ID = new ObjectId("6953de7b4c64681e81e0aec9");

// ============================================================================
// WARDROBE ITEMS WITH IMAGES (Using Unsplash for high-quality free images)
// ============================================================================

const WARDROBE_ITEMS = [
  // ==================== ANGELA CRUZ - Mid-60s Homemaker ====================
  {
    name: "Angela's Floral House Dress",
    type: "DRESS",
    description: "A comfortable cotton house dress with delicate floral patterns.",
    promptText: "wearing a soft cotton house dress with small blue and pink floral print, loose comfortable fit, mid-length hemline below the knee, short sleeves, modest neckline",
    negativePrompt: "tight fitting, revealing, modern fashion",
    color: "blue and pink floral",
    pattern: "floral",
    material: "cotton",
    style: "homely",
    tags: ["homemaker", "comfortable", "elderly", "domestic", "floral", "modest"],
    category: "casual",
    gender: "FEMALE",
    ageGroup: "ELDERLY",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Angela Cruz",
    imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=500&fit=crop",
  },
  {
    name: "Angela's Gardening Apron",
    type: "ACCESSORY",
    description: "A well-worn canvas gardening apron with multiple pockets.",
    promptText: "wearing a faded green canvas gardening apron with large front pockets, soil stains visible, worn and well-used appearance, tied at the waist",
    color: "faded green",
    material: "canvas",
    style: "utilitarian",
    tags: ["gardening", "apron", "work", "stained", "practical"],
    category: "workwear",
    gender: "FEMALE",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Angela Cruz",
    imageUrl: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=400&h=500&fit=crop",
  },
  {
    name: "Angela's Comfortable Cardigan",
    type: "OUTERWEAR",
    description: "A cozy knitted cardigan in warm earth tones.",
    promptText: "wearing a soft knitted cardigan in warm brown tone, chunky knit texture, wooden buttons, slightly oversized comfortable fit, reaching mid-hip",
    color: "warm brown",
    pattern: "knit",
    material: "wool blend",
    style: "cozy",
    tags: ["cardigan", "cozy", "knitted", "comfortable", "warm"],
    category: "casual",
    gender: "FEMALE",
    ageGroup: "ELDERLY",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Angela Cruz",
    imageUrl: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400&h=500&fit=crop",
  },
  {
    name: "Angela's House Slippers",
    type: "FOOTWEAR",
    description: "Simple, well-worn house slippers.",
    promptText: "wearing worn fabric house slippers in muted pink, soft padded soles, slightly scuffed from daily use",
    color: "muted pink",
    material: "fabric",
    style: "comfortable",
    tags: ["slippers", "house", "comfortable", "worn"],
    category: "sleepwear",
    gender: "FEMALE",
    ageGroup: "ELDERLY",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Angela Cruz",
    imageUrl: "https://images.unsplash.com/photo-1631541909061-71e349d1f203?w=400&h=500&fit=crop",
  },

  // ==================== RICARDO COSTA RIBEIRO - Late 40s Videomaker ====================
  {
    name: "Ricardo's Professional Polo",
    type: "TOP",
    description: "A clean, understated polo shirt for a professional videomaker.",
    promptText: "wearing a crisp navy blue polo shirt, premium cotton fabric, neat collar, subtle texture, professional but casual appearance",
    color: "navy blue",
    material: "cotton",
    style: "smart casual",
    tags: ["professional", "polo", "understated", "quality", "videomaker"],
    category: "workwear",
    gender: "MALE",
    ageGroup: "ADULT",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Ricardo Costa Ribeiro",
    imageUrl: "https://images.unsplash.com/photo-1626497764746-6dc36546b388?w=400&h=500&fit=crop",
  },
  {
    name: "Ricardo's Cargo Pants",
    type: "BOTTOM",
    description: "Practical cargo pants with multiple pockets for tech equipment.",
    promptText: "wearing dark gray cargo pants with multiple utility pockets, durable fabric, comfortable fit for long work days",
    color: "dark gray",
    material: "cotton blend",
    style: "utilitarian",
    tags: ["cargo", "practical", "pockets", "professional", "tech"],
    category: "workwear",
    gender: "MALE",
    ageGroup: "ADULT",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Ricardo Costa Ribeiro",
    imageUrl: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400&h=500&fit=crop",
  },
  {
    name: "Ricardo's Tech Vest",
    type: "OUTERWEAR",
    description: "A multi-pocket vest for carrying camera accessories.",
    promptText: "wearing a black tactical photography vest with numerous pockets and compartments, lightweight mesh backing, professional videographer appearance",
    color: "black",
    material: "nylon",
    style: "technical",
    tags: ["vest", "photography", "tactical", "professional", "equipment"],
    category: "workwear",
    gender: "MALE",
    ageGroup: "ADULT",
    rarity: "UNCOMMON",
    isPublic: true,
    characterName: "Ricardo Costa Ribeiro",
    imageUrl: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=500&fit=crop",
  },
  {
    name: "Ricardo's Comfortable Sneakers",
    type: "FOOTWEAR",
    description: "Quality sneakers for long days on set.",
    promptText: "wearing clean white leather sneakers with minimal design, comfortable cushioned soles, pristine condition",
    color: "white",
    material: "leather",
    style: "minimalist",
    tags: ["sneakers", "comfortable", "professional", "clean", "minimal"],
    category: "casual",
    gender: "MALE",
    ageGroup: "ADULT",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Ricardo Costa Ribeiro",
    imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=500&fit=crop",
  },

  // ==================== PEDRO MARTINEZ - 15-year-old Tech Kid ====================
  {
    name: "Pedro's Graphic Hoodie",
    type: "OUTERWEAR",
    description: "An oversized hoodie with subtle tech/conspiracy-themed graphics.",
    promptText: "wearing an oversized dark gray hoodie with subtle geometric pattern print, hood down, slightly faded from washing, comfortable teen style",
    color: "dark gray",
    pattern: "geometric print",
    material: "cotton fleece",
    style: "streetwear",
    tags: ["hoodie", "teen", "oversized", "comfortable", "conspiracy", "tech"],
    category: "casual",
    gender: "MALE",
    ageGroup: "TEEN",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Pedro Martinez",
    imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=500&fit=crop",
  },
  {
    name: "Pedro's Worn Jeans",
    type: "BOTTOM",
    description: "Comfortable worn-in jeans, slightly baggy in teen style.",
    promptText: "wearing faded blue jeans with natural wear marks at the knees, slightly loose fit, rolled cuffs, comfortable teenager style",
    color: "faded blue",
    material: "denim",
    style: "casual",
    tags: ["jeans", "worn", "teen", "comfortable", "casual"],
    category: "casual",
    gender: "MALE",
    ageGroup: "TEEN",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Pedro Martinez",
    imageUrl: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=500&fit=crop",
  },
  {
    name: "Pedro's Thick-Framed Glasses",
    type: "EYEWEAR",
    description: "Characteristic thick-framed glasses for the nerdy teen.",
    promptText: "wearing thick black rectangular glasses frames, slightly oversized for face, nerdy intellectual appearance, clean lenses",
    color: "black",
    material: "plastic",
    style: "nerdy",
    tags: ["glasses", "nerd", "teen", "intellectual", "thick-framed"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "TEEN",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Pedro Martinez",
    imageUrl: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&h=500&fit=crop",
  },
  {
    name: "Pedro's Beat-Up Sneakers",
    type: "FOOTWEAR",
    description: "Well-worn skateboard-style sneakers.",
    promptText: "wearing scuffed black canvas sneakers with white rubber soles, visible wear marks, frayed laces, skater style",
    color: "black",
    material: "canvas",
    style: "skater",
    tags: ["sneakers", "worn", "teen", "skater", "canvas"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "TEEN",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Pedro Martinez",
    imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400&h=500&fit=crop",
  },

  // ==================== KATHRINE HIAMERTAS GARCIA - 17-year-old British ====================
  {
    name: "Kathrine's School Blazer",
    type: "OUTERWEAR",
    description: "A proper British school-style blazer from Norwich.",
    promptText: "wearing a fitted navy blue school blazer with brass buttons, structured shoulders, British prep school style",
    color: "navy blue",
    material: "wool blend",
    style: "preppy",
    tags: ["blazer", "british", "school", "formal", "teen"],
    category: "formal",
    gender: "FEMALE",
    ageGroup: "TEEN",
    rarity: "UNCOMMON",
    isPublic: true,
    characterName: "Kathrine Hiamertas Garcia",
    imageUrl: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&h=500&fit=crop",
  },
  {
    name: "Kathrine's Plain Button-Up",
    type: "TOP",
    description: "A crisp white button-up shirt reflecting her serious demeanor.",
    promptText: "wearing a crisp white cotton button-up shirt, neat collar, sleeves rolled to elbows, tucked in, serious student appearance",
    color: "white",
    material: "cotton",
    style: "classic",
    tags: ["shirt", "formal", "student", "british", "crisp"],
    category: "formal",
    gender: "FEMALE",
    ageGroup: "TEEN",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Kathrine Hiamertas Garcia",
    imageUrl: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&h=500&fit=crop",
  },
  {
    name: "Kathrine's Dark Skirt",
    type: "BOTTOM",
    description: "A knee-length dark skirt appropriate for a serious student.",
    promptText: "wearing a knee-length dark gray pleated skirt, modest hem, school-appropriate, British student style",
    color: "dark gray",
    material: "wool blend",
    style: "classic",
    tags: ["skirt", "pleated", "school", "modest", "british"],
    category: "formal",
    gender: "FEMALE",
    ageGroup: "TEEN",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Kathrine Hiamertas Garcia",
    imageUrl: "https://images.unsplash.com/photo-1583496661160-fb5886a0uj12?w=400&h=500&fit=crop",
  },
  {
    name: "Kathrine's Mary Janes",
    type: "FOOTWEAR",
    description: "Classic black Mary Jane shoes, practical and proper.",
    promptText: "wearing classic black leather Mary Jane shoes with low heel, single strap across instep, polished finish",
    color: "black",
    material: "leather",
    style: "classic",
    tags: ["mary jane", "school", "british", "formal", "classic"],
    category: "formal",
    gender: "FEMALE",
    ageGroup: "TEEN",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Kathrine Hiamertas Garcia",
    imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=500&fit=crop",
  },

  // ==================== NICOLE OLIVEIRA GARCIA - Mid-30s Model ====================
  {
    name: "Nicole's Designer Dress",
    type: "DRESS",
    description: "An elegant designer dress for photo shoots and appearances.",
    promptText: "wearing an elegant form-fitting designer dress in deep emerald green, sophisticated cut, above-knee length, subtle shimmer fabric",
    color: "emerald green",
    material: "silk blend",
    style: "high fashion",
    tags: ["designer", "elegant", "model", "sophisticated", "fashion"],
    category: "evening",
    gender: "FEMALE",
    ageGroup: "ADULT",
    rarity: "RARE",
    isPublic: true,
    characterName: "Nicole Oliveira Garcia",
    imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=500&fit=crop",
  },
  {
    name: "Nicole's Casual Chic Top",
    type: "TOP",
    description: "A stylish yet casual top for off-duty model moments.",
    promptText: "wearing a loose-fitting cream silk blouse with delicate draping, effortlessly stylish, off-duty model aesthetic",
    color: "cream",
    material: "silk",
    style: "casual chic",
    tags: ["blouse", "silk", "model", "stylish", "casual"],
    category: "casual",
    gender: "FEMALE",
    ageGroup: "ADULT",
    rarity: "UNCOMMON",
    isPublic: true,
    characterName: "Nicole Oliveira Garcia",
    imageUrl: "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=400&h=500&fit=crop",
  },
  {
    name: "Nicole's High-Waisted Jeans",
    type: "BOTTOM",
    description: "Perfectly fitted high-waisted jeans showing off her model figure.",
    promptText: "wearing perfectly fitted high-waisted dark blue jeans, flattering cut, no rips or distressing, polished casual appearance",
    color: "dark blue",
    material: "premium denim",
    style: "polished casual",
    tags: ["jeans", "high-waisted", "model", "fitted", "premium"],
    category: "casual",
    gender: "FEMALE",
    ageGroup: "ADULT",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Nicole Oliveira Garcia",
    imageUrl: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&h=500&fit=crop",
  },
  {
    name: "Nicole's Stiletto Heels",
    type: "FOOTWEAR",
    description: "Classic black stiletto heels, essential for any model.",
    promptText: "wearing sleek black stiletto heels with pointed toe, 4-inch heel, polished leather finish, runway-ready appearance",
    color: "black",
    material: "leather",
    style: "high fashion",
    tags: ["heels", "stiletto", "model", "elegant", "runway"],
    category: "evening",
    gender: "FEMALE",
    ageGroup: "ADULT",
    rarity: "UNCOMMON",
    isPublic: true,
    characterName: "Nicole Oliveira Garcia",
    imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&h=500&fit=crop",
  },

  // ==================== OLD MAN SANTOS - 82-year-old Storyteller ====================
  {
    name: "Old Man Santos's Worn Suit Jacket",
    type: "OUTERWEAR",
    description: "An old but clean suit jacket from decades past.",
    promptText: "wearing an old brown tweed suit jacket with visible wear at the elbows, patched but clean, outdated style from decades ago, dignified despite age",
    color: "brown tweed",
    material: "tweed",
    style: "vintage",
    tags: ["jacket", "old", "worn", "tweed", "dignified", "elderly"],
    category: "formal",
    gender: "MALE",
    ageGroup: "ELDERLY",
    rarity: "UNCOMMON",
    isPublic: true,
    characterName: "Old Man Santos",
    imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&h=500&fit=crop",
  },
  {
    name: "Old Man Santos's Flat Cap",
    type: "HEADWEAR",
    description: "A traditional flat cap he always wears in the park.",
    promptText: "wearing a traditional gray wool flat cap, slightly faded, well-shaped from years of use, classic elderly gentleman style",
    color: "gray",
    material: "wool",
    style: "traditional",
    tags: ["cap", "flat cap", "traditional", "elderly", "gentleman"],
    category: "casual",
    gender: "MALE",
    ageGroup: "ELDERLY",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Old Man Santos",
    imageUrl: "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=400&h=500&fit=crop",
  },
  {
    name: "Old Man Santos's Walking Cane",
    type: "ACCESSORY",
    description: "A wooden walking cane with a carved handle.",
    promptText: "holding a worn wooden walking cane with carved handle, dark varnished wood, smooth from years of use",
    color: "dark wood",
    material: "wood",
    style: "classic",
    tags: ["cane", "walking stick", "elderly", "wooden", "carved"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "ELDERLY",
    rarity: "COMMON",
    isPublic: true,
    characterName: "Old Man Santos",
    imageUrl: "https://images.unsplash.com/photo-1631857455684-a1c4e2a2ec5c?w=400&h=500&fit=crop",
  },

  // ==================== COMMON WARDROBE ITEMS ====================
  {
    name: "Basic White T-Shirt",
    type: "TOP",
    description: "A simple, versatile white cotton t-shirt.",
    promptText: "wearing a plain white cotton t-shirt, crew neck, comfortable fit, basic casual style",
    color: "white",
    material: "cotton",
    style: "basic",
    tags: ["basic", "t-shirt", "casual", "versatile", "white"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=500&fit=crop",
  },
  {
    name: "Black Leather Jacket",
    type: "OUTERWEAR",
    description: "A classic black leather motorcycle jacket.",
    promptText: "wearing a classic black leather motorcycle jacket with silver zippers, worn-in patina, rebel aesthetic, fitted silhouette",
    color: "black",
    material: "leather",
    style: "rebel",
    tags: ["leather", "jacket", "motorcycle", "rebel", "classic"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "ADULT",
    rarity: "UNCOMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=500&fit=crop",
  },
  {
    name: "Blue Denim Jacket",
    type: "OUTERWEAR",
    description: "A classic medium-wash denim jacket.",
    promptText: "wearing a medium-wash blue denim jacket, brass buttons, slightly faded, classic American casual style",
    color: "medium blue",
    material: "denim",
    style: "casual",
    tags: ["denim", "jacket", "casual", "classic", "american"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=400&h=500&fit=crop",
  },
  {
    name: "Gray Crewneck Sweater",
    type: "TOP",
    description: "A comfortable gray crewneck sweater.",
    promptText: "wearing a soft gray crewneck sweater, relaxed fit, fine knit texture, cozy casual appearance",
    color: "gray",
    material: "cotton knit",
    style: "casual",
    tags: ["sweater", "gray", "crewneck", "comfortable", "basic"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=400&h=500&fit=crop",
  },
  {
    name: "Black Dress Pants",
    type: "BOTTOM",
    description: "Classic black dress pants for formal occasions.",
    promptText: "wearing crisp black dress pants with sharp crease, tailored fit, formal professional appearance",
    color: "black",
    material: "wool blend",
    style: "formal",
    tags: ["dress pants", "formal", "black", "professional", "tailored"],
    category: "formal",
    gender: "UNISEX",
    ageGroup: "ADULT",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&h=500&fit=crop",
  },
  {
    name: "Khaki Chinos",
    type: "BOTTOM",
    description: "Versatile khaki chino pants.",
    promptText: "wearing khaki chino pants, straight leg fit, cotton twill fabric, smart casual appearance",
    color: "khaki",
    material: "cotton twill",
    style: "smart casual",
    tags: ["chinos", "khaki", "casual", "versatile", "smart"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400&h=500&fit=crop",
  },
  {
    name: "Running Shoes",
    type: "FOOTWEAR",
    description: "Athletic running shoes with modern design.",
    promptText: "wearing modern athletic running shoes with mesh upper, cushioned soles, sporty appearance, bright accent colors",
    color: "black with accent",
    material: "mesh and rubber",
    style: "athletic",
    tags: ["running", "athletic", "sporty", "comfortable", "modern"],
    category: "athletic",
    gender: "UNISEX",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=500&fit=crop",
  },
  {
    name: "Classic Oxford Shoes",
    type: "FOOTWEAR",
    description: "Traditional brown leather Oxford shoes.",
    promptText: "wearing classic brown leather Oxford shoes with brogue detailing, polished finish, formal elegant appearance",
    color: "brown",
    material: "leather",
    style: "classic",
    tags: ["oxford", "formal", "leather", "brogue", "elegant"],
    category: "formal",
    gender: "MALE",
    ageGroup: "ADULT",
    rarity: "UNCOMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400&h=500&fit=crop",
  },
  {
    name: "Baseball Cap",
    type: "HEADWEAR",
    description: "A casual baseball cap.",
    promptText: "wearing a simple black baseball cap with curved brim, casual sporty style, slightly worn",
    color: "black",
    material: "cotton",
    style: "sporty",
    tags: ["cap", "baseball", "casual", "sporty"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400&h=500&fit=crop",
  },
  {
    name: "Wool Beanie",
    type: "HEADWEAR",
    description: "A warm knitted wool beanie.",
    promptText: "wearing a thick knitted wool beanie in dark gray, rolled cuff, cozy winter style",
    color: "dark gray",
    material: "wool",
    style: "casual",
    tags: ["beanie", "winter", "knit", "warm", "casual"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=400&h=500&fit=crop",
  },
  {
    name: "Leather Watch",
    type: "ACCESSORY",
    description: "A classic leather-strap wristwatch.",
    promptText: "wearing a classic wristwatch with brown leather strap, silver case, elegant timepiece",
    color: "brown and silver",
    material: "leather and metal",
    style: "classic",
    tags: ["watch", "leather", "elegant", "classic", "timepiece"],
    category: "formal",
    gender: "UNISEX",
    ageGroup: "ADULT",
    rarity: "UNCOMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=500&fit=crop",
  },
  {
    name: "Simple Gold Necklace",
    type: "JEWELRY",
    description: "A delicate gold chain necklace.",
    promptText: "wearing a delicate thin gold chain necklace, simple elegant design, subtle shine",
    color: "gold",
    material: "gold",
    style: "elegant",
    tags: ["necklace", "gold", "delicate", "elegant", "simple"],
    category: "formal",
    gender: "FEMALE",
    ageGroup: "ADULT",
    rarity: "UNCOMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=500&fit=crop",
  },
  {
    name: "Aviator Sunglasses",
    type: "EYEWEAR",
    description: "Classic aviator-style sunglasses.",
    promptText: "wearing classic gold-frame aviator sunglasses with dark tinted lenses, timeless cool style",
    color: "gold frame",
    material: "metal and glass",
    style: "classic",
    tags: ["sunglasses", "aviator", "classic", "cool", "timeless"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "ADULT",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=500&fit=crop",
  },
  {
    name: "Canvas Backpack",
    type: "BAG",
    description: "A practical canvas backpack for everyday use.",
    promptText: "carrying a weathered olive canvas backpack with leather straps, multiple pockets, utilitarian style",
    color: "olive",
    material: "canvas and leather",
    style: "utilitarian",
    tags: ["backpack", "canvas", "practical", "everyday", "casual"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=500&fit=crop",
  },
  {
    name: "Leather Messenger Bag",
    type: "BAG",
    description: "A professional leather messenger bag.",
    promptText: "carrying a brown leather messenger bag with brass buckle, worn patina, professional appearance",
    color: "brown",
    material: "leather",
    style: "professional",
    tags: ["messenger bag", "leather", "professional", "work", "business"],
    category: "workwear",
    gender: "UNISEX",
    ageGroup: "ADULT",
    rarity: "UNCOMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=500&fit=crop",
  },
  {
    name: "Hospital Scrubs",
    type: "UNIFORM",
    description: "Standard hospital scrubs for medical personnel.",
    promptText: "wearing light blue hospital scrubs, v-neck top with drawstring pants, comfortable medical professional attire",
    color: "light blue",
    material: "polyester blend",
    style: "medical",
    tags: ["scrubs", "medical", "hospital", "nurse", "doctor", "uniform"],
    category: "workwear",
    gender: "UNISEX",
    ageGroup: "ADULT",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=400&h=500&fit=crop",
  },
  {
    name: "Lab Coat",
    type: "UNIFORM",
    description: "A white laboratory coat for scientists.",
    promptText: "wearing a crisp white lab coat with chest pocket, knee-length, professional scientist appearance",
    color: "white",
    material: "cotton",
    style: "professional",
    tags: ["lab coat", "scientist", "medical", "professional", "research"],
    category: "workwear",
    gender: "UNISEX",
    ageGroup: "ADULT",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1576671081837-49000212a370?w=400&h=500&fit=crop",
  },
  {
    name: "Raincoat",
    type: "OUTERWEAR",
    description: "A practical waterproof raincoat.",
    promptText: "wearing a dark navy waterproof raincoat with hood, button front, reaching mid-thigh, practical rain protection",
    color: "navy",
    material: "waterproof nylon",
    style: "practical",
    tags: ["raincoat", "waterproof", "practical", "weather", "hood"],
    category: "outerwear",
    gender: "UNISEX",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1545594861-3bef43ff2fc8?w=400&h=500&fit=crop",
  },
  {
    name: "Winter Parka",
    type: "OUTERWEAR",
    description: "A warm winter parka with fur-lined hood.",
    promptText: "wearing a thick winter parka in black with faux fur-lined hood, insulated, snow-ready, reaching mid-thigh",
    color: "black",
    material: "nylon with insulation",
    style: "winter",
    tags: ["parka", "winter", "warm", "fur hood", "insulated"],
    category: "outerwear",
    gender: "UNISEX",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1544923246-77307dd628b8?w=400&h=500&fit=crop",
  },
  {
    name: "Silk Evening Gown",
    type: "DRESS",
    description: "An elegant floor-length silk evening gown.",
    promptText: "wearing a stunning floor-length silk evening gown in deep burgundy, flowing fabric, elegant draping, formal event attire",
    color: "burgundy",
    material: "silk",
    style: "formal",
    tags: ["gown", "evening", "silk", "elegant", "formal", "floor-length"],
    category: "evening",
    gender: "FEMALE",
    ageGroup: "ADULT",
    rarity: "RARE",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=400&h=500&fit=crop",
  },
  {
    name: "Business Suit",
    type: "FULL_OUTFIT",
    description: "A complete professional business suit.",
    promptText: "wearing a tailored charcoal gray business suit with white dress shirt and dark tie, polished professional appearance, executive style",
    color: "charcoal gray",
    material: "wool",
    style: "formal",
    tags: ["suit", "business", "professional", "formal", "executive"],
    category: "formal",
    gender: "MALE",
    ageGroup: "ADULT",
    rarity: "UNCOMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&h=500&fit=crop",
  },
  {
    name: "Summer Sundress",
    type: "DRESS",
    description: "A light, breezy sundress for warm weather.",
    promptText: "wearing a light cotton sundress with thin straps, flowing skirt, floral print on white background, summer casual style",
    color: "white with floral",
    pattern: "floral",
    material: "cotton",
    style: "casual",
    tags: ["sundress", "summer", "floral", "light", "casual"],
    category: "casual",
    gender: "FEMALE",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&h=500&fit=crop",
  },
  {
    name: "Wool Scarf",
    type: "SCARF",
    description: "A cozy wool scarf for cold weather.",
    promptText: "wearing a thick wool scarf in burgundy and gray plaid pattern, wrapped loosely around neck, cozy winter accessory",
    color: "burgundy and gray",
    pattern: "plaid",
    material: "wool",
    style: "casual",
    tags: ["scarf", "wool", "winter", "plaid", "cozy"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=500&fit=crop",
  },
  {
    name: "Leather Belt",
    type: "BELT",
    description: "A classic brown leather belt.",
    promptText: "wearing a classic brown leather belt with simple silver buckle, clean professional accessory",
    color: "brown",
    material: "leather",
    style: "classic",
    tags: ["belt", "leather", "classic", "professional", "brown"],
    category: "formal",
    gender: "UNISEX",
    ageGroup: "ANY",
    rarity: "COMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a45?w=400&h=500&fit=crop",
  },
  {
    name: "Leather Gloves",
    type: "GLOVES",
    description: "Elegant black leather gloves.",
    promptText: "wearing fitted black leather gloves, smooth finish, elegant winter accessory",
    color: "black",
    material: "leather",
    style: "elegant",
    tags: ["gloves", "leather", "black", "winter", "elegant"],
    category: "formal",
    gender: "UNISEX",
    ageGroup: "ADULT",
    rarity: "UNCOMMON",
    isPublic: true,
    imageUrl: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=400&h=500&fit=crop",
  },

  // ==================== SPECIAL/UNIQUE ITEMS ====================
  {
    name: "Spider-Embroidered Shawl",
    type: "ACCESSORY",
    description: "A mysterious dark shawl with subtle spider web embroidery - significant to the TCH story.",
    promptText: "wearing a dark burgundy shawl with delicate silver spider web embroidery along the edges, mysterious elegant appearance, subtle supernatural hint",
    color: "burgundy with silver",
    pattern: "spider web embroidery",
    material: "silk",
    style: "mysterious",
    tags: ["shawl", "spider", "mysterious", "supernatural", "embroidered", "TCH"],
    category: "evening",
    gender: "FEMALE",
    ageGroup: "ANY",
    rarity: "LEGENDARY",
    isPublic: true,
    restrictedToConditions: ["supernatural_event", "revelation_scene"],
    imageUrl: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=500&fit=crop",
  },
  {
    name: "Meteorite Pendant",
    type: "JEWELRY",
    description: "A pendant made from meteorite material - connected to the alien origin story.",
    promptText: "wearing a pendant with dark metallic meteorite fragment on silver chain, unusual crystalline patterns visible, otherworldly appearance",
    color: "dark metallic",
    material: "meteorite and silver",
    style: "unique",
    tags: ["pendant", "meteorite", "alien", "supernatural", "unique", "TCH"],
    category: "casual",
    gender: "UNISEX",
    ageGroup: "ANY",
    rarity: "LEGENDARY",
    isPublic: true,
    restrictedToConditions: ["supernatural_event", "alien_connection"],
    imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=500&fit=crop",
  },
];

async function reseedWardrobe() {
  const client = new MongoClient(MONGODB_URI);
  
  try {
    await client.connect();
    console.log("Connected to MongoDB");
    
    const db = client.db(DB_NAME);
    const collection = db.collection("communityWardrobe");
    
    // Drop existing collection to re-seed with images
    console.log("Dropping existing wardrobe collection...");
    await collection.drop().catch(() => console.log("Collection didn't exist, creating new..."));
    
    // Create indexes
    await collection.createIndex({ type: 1, isPublic: 1 });
    await collection.createIndex({ tags: 1 });
    await collection.createIndex({ characterEntityId: 1 });
    await collection.createIndex({ rarity: 1 });
    await collection.createIndex({ usageCount: -1 });
    await collection.createIndex({ 
      name: "text", 
      description: "text", 
      tags: "text",
      promptText: "text",
    });
    
    console.log("Indexes created");
    
    // Insert all wardrobe items with images
    const now = new Date();
    const itemsToInsert = WARDROBE_ITEMS.map(item => ({
      _id: new ObjectId(),
      ...item,
      usageCount: 0,
      favoriteCount: 0,
      createdAt: now,
      createdBy: SYSTEM_USER_ID,
      updatedAt: now,
      updatedBy: SYSTEM_USER_ID,
    }));
    
    const result = await collection.insertMany(itemsToInsert);
    console.log(`\n✅ Inserted ${result.insertedCount} wardrobe items with images!`);
    
    // Summary
    const withImages = WARDROBE_ITEMS.filter(i => i.imageUrl).length;
    console.log(`\n📸 Items with images: ${withImages}/${WARDROBE_ITEMS.length}`);
    
  } catch (err) {
    console.error("Error seeding wardrobe:", err);
  } finally {
    await client.close();
    console.log("\nDisconnected from MongoDB");
  }
}

reseedWardrobe();
